FactoryBot.define do
  factory :pcp_credential do
    practitioner_number { "MyString" }
    ssn { "MyString" }
    dea_state { 1 }
    expiration_date { "2026-03-19" }
    medical_license_number { "MyString" }
    medical_license_state { 1 }
    medical_license_expiration_date { "2026-03-19" }
    board_certified_status { false }
    hospital_certification_name { "MyString" }
    practitioner_birth_date { "2026-03-19" }
    languages_spoken { "MyString" }
    medicare_identifier { "MyString" }
    email { "MyString" }
    insurance_carrier { "MyString" }
    insurance_coverage_amount { 1.5 }
    insurance_expiration_date { "2026-03-19" }
    medical_school { "MyString" }
    residency { "MyString" }
    years_practicing { 1 }
    pcp_id { "" }
    pcp_group_id { "" }
    npi { "MyString" }
    gender { 1 }
    speciality { 1 }
    middle_initial { "MyString" }
    first_name { "MyString" }
    last_name { "MyString" }
    accepting_new_patients { false }
    lowest_age_accepted { 1 }
    highest_age_accepted { 1 }
    title_degree { 1 }
    practitioner_role { 1 }
    status { 1 }
    tax_id { "MyString" }
    document_1 { "MyString" }
    document_2 { "MyString" }
    document_3 { "MyString" }
    receipt_confirmed { false }
    dea_number { "MyString" }
    approved { false }
    board_certification_expiration_date { "2026-03-19" }
    board_certification_effective_date { "2026-03-19" }
    board_certification_effective_type { "MyString" }
    board_certification_type { "MyString" }
    board_certification_type_secondary { "MyString" }
    board_certification_effective_date_secondary { "2026-03-19" }
    primary_language { "MyString" }
    secondary_language { "MyString" }
    third_language { "MyString" }
    taxonomy_code { 1 }
    secondary_speciality { "MyString" }
    medicaid_number { "MyString" }
    phone_number { "MyString" }
    insurance_policy_number { "MyString" }
    insurance_effective_date { "MyString" }
    approval_date { "2026-03-19" }
    pcp_group_npi { "MyString" }
    pcp_group_tax_id { "MyString" }
    pcp_group_billing_address { "MyString" }
    pcp_group_billing_phone { "MyString" }
    board_certification_type_expiration_date_secondary { "MyString" }
    insurance_coverage_amount_aggregate { 1.5 }
    work_history_notes { "MyText" }
    cv { "MyString" }
    additional_document { "MyString" }
  end
end
